<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827191734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE manifest_technology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, technology VARCHAR(20) NOT NULL, version VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL, manifest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECAA5851E697B2FB ON manifest_technology (manifest_id)');
        $this->addSql('CREATE UNIQUE INDEX manifest_technology_unique ON manifest_technology (manifest_id, technology)');
        $this->addSql('ALTER TABLE manifest_technology ADD CONSTRAINT FK_ECAA5851E697B2FB FOREIGN KEY (manifest_id) REFERENCES manifest (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE manifest_technology DROP CONSTRAINT FK_ECAA5851E697B2FB');
        $this->addSql('DROP TABLE manifest_technology');
    }
}
