<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260827181739 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA IF NOT EXISTS public');
        $this->addSql('CREATE TABLE app_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, github_token VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE dependency (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_constraint VARCHAR(255) NOT NULL, locked_version VARCHAR(255) NOT NULL, dependency_type VARCHAR(255) NOT NULL, manifest_id INT NOT NULL, package_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2F585505E697B2FB ON dependency (manifest_id)');
        $this->addSql('CREATE INDEX IDX_2F585505F44CABFF ON dependency (package_id)');
        $this->addSql('CREATE TABLE dependency_manager (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_142D3EFF5E237E06 ON dependency_manager (name)');
        $this->addSql('CREATE TABLE manifest (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, lock_path VARCHAR(255) DEFAULT NULL, project_id UUID NOT NULL, dependency_manager_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A6FA6840166D1F9C ON manifest (project_id)');
        $this->addSql('CREATE INDEX IDX_A6FA6840DCC3B6C1 ON manifest (dependency_manager_id)');
        $this->addSql('CREATE UNIQUE INDEX project_path_unique ON manifest (project_id, path)');
        $this->addSql('CREATE TABLE package (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, vendor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DE686795F603EE73 ON package (vendor_id)');
        $this->addSql('CREATE UNIQUE INDEX vendor_name_unique ON package (vendor_id, name)');
        $this->addSql('CREATE TABLE project (id UUID NOT NULL, name VARCHAR(255) NOT NULL, ssh_link VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE scan (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, error TEXT DEFAULT NULL, manifest_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4B3B3AEE697B2FB ON scan (manifest_id)');
        $this->addSql('CREATE TABLE technology_release_cycle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, technology VARCHAR(20) NOT NULL, cycle VARCHAR(20) NOT NULL, latest_version VARCHAR(255) NOT NULL, lts BOOLEAN NOT NULL, release_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, eol_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX technology_cycle_unique ON technology_release_cycle (technology, cycle)');
        $this->addSql('CREATE TABLE vendor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, dependency_manager_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F52233F6DCC3B6C1 ON vendor (dependency_manager_id)');
        $this->addSql('CREATE TABLE version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version VARCHAR(255) NOT NULL, normalized_version VARCHAR(255) NOT NULL, released_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, runtime_constraint VARCHAR(255) DEFAULT NULL, stability VARCHAR(20) NOT NULL, package_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF1CD3C3F44CABFF ON version (package_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('CREATE TABLE cache_items (item_id VARCHAR(255) NOT NULL, item_data BYTEA NOT NULL, item_lifetime INT DEFAULT NULL, item_time INT NOT NULL, PRIMARY KEY (item_id))');
        $this->addSql('ALTER TABLE dependency ADD CONSTRAINT FK_2F585505E697B2FB FOREIGN KEY (manifest_id) REFERENCES manifest (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dependency ADD CONSTRAINT FK_2F585505F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manifest ADD CONSTRAINT FK_A6FA6840166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manifest ADD CONSTRAINT FK_A6FA6840DCC3B6C1 FOREIGN KEY (dependency_manager_id) REFERENCES dependency_manager (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE686795F603EE73 FOREIGN KEY (vendor_id) REFERENCES vendor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE scan ADD CONSTRAINT FK_C4B3B3AEE697B2FB FOREIGN KEY (manifest_id) REFERENCES manifest (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vendor ADD CONSTRAINT FK_F52233F6DCC3B6C1 FOREIGN KEY (dependency_manager_id) REFERENCES dependency_manager (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C3F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dependency DROP CONSTRAINT FK_2F585505E697B2FB');
        $this->addSql('ALTER TABLE dependency DROP CONSTRAINT FK_2F585505F44CABFF');
        $this->addSql('ALTER TABLE manifest DROP CONSTRAINT FK_A6FA6840166D1F9C');
        $this->addSql('ALTER TABLE manifest DROP CONSTRAINT FK_A6FA6840DCC3B6C1');
        $this->addSql('ALTER TABLE package DROP CONSTRAINT FK_DE686795F603EE73');
        $this->addSql('ALTER TABLE scan DROP CONSTRAINT FK_C4B3B3AEE697B2FB');
        $this->addSql('ALTER TABLE vendor DROP CONSTRAINT FK_F52233F6DCC3B6C1');
        $this->addSql('ALTER TABLE version DROP CONSTRAINT FK_BF1CD3C3F44CABFF');
        $this->addSql('DROP TABLE app_settings');
        $this->addSql('DROP TABLE dependency');
        $this->addSql('DROP TABLE dependency_manager');
        $this->addSql('DROP TABLE manifest');
        $this->addSql('DROP TABLE package');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE scan');
        $this->addSql('DROP TABLE technology_release_cycle');
        $this->addSql('DROP TABLE vendor');
        $this->addSql('DROP TABLE version');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE cache_items');
    }
}
