<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827190345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE vulnerability (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR(255) NOT NULL, affected_version VARCHAR(255) NOT NULL, summary TEXT DEFAULT NULL, severity VARCHAR(32) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, package_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C4E4047F44CABFF ON vulnerability (package_id)');
        $this->addSql('CREATE UNIQUE INDEX package_external_id_version_unique ON vulnerability (package_id, external_id, affected_version)');
        $this->addSql('ALTER TABLE vulnerability ADD CONSTRAINT FK_6C4E4047F44CABFF FOREIGN KEY (package_id) REFERENCES package (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vulnerability DROP CONSTRAINT FK_6C4E4047F44CABFF');
        $this->addSql('DROP TABLE vulnerability');
    }
}
